# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'factoryTestToolUI.ui'
#
# Created: Tue Jan 23 20:38:38 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 686)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 686))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 686))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icon/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 165, 1000, 3))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.twTestArea = QtGui.QTabWidget(self.centralwidget)
        self.twTestArea.setGeometry(QtCore.QRect(5, 171, 990, 471))
        self.twTestArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.twTestArea.setObjectName(_fromUtf8("twTestArea"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.textBrowser_4 = QtGui.QTextBrowser(self.tab)
        self.textBrowser_4.setEnabled(False)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 10, 231, 431))
        self.textBrowser_4.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.textBrowser_5 = QtGui.QTextBrowser(self.tab)
        self.textBrowser_5.setEnabled(True)
        self.textBrowser_5.setGeometry(QtCore.QRect(10, 10, 231, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);\n"
"color: rgb(85, 0, 0);"))
        self.textBrowser_5.setObjectName(_fromUtf8("textBrowser_5"))
        self.leStatus1 = QtGui.QLineEdit(self.tab)
        self.leStatus1.setEnabled(True)
        self.leStatus1.setGeometry(QtCore.QRect(12, 84, 227, 102))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leStatus1.sizePolicy().hasHeightForWidth())
        self.leStatus1.setSizePolicy(sizePolicy)
        self.leStatus1.setMinimumSize(QtCore.QSize(60, 50))
        self.leStatus1.setMaximumSize(QtCore.QSize(9999999, 9999999))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bauhaus 93"))
        font.setPointSize(48)
        self.leStatus1.setFont(font)
        self.leStatus1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.leStatus1.setMouseTracking(True)
        self.leStatus1.setAcceptDrops(True)
        self.leStatus1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leStatus1.setAutoFillBackground(False)
        self.leStatus1.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);"))
        self.leStatus1.setText(_fromUtf8(" IDLE"))
        self.leStatus1.setAlignment(QtCore.Qt.AlignCenter)
        self.leStatus1.setReadOnly(True)
        self.leStatus1.setObjectName(_fromUtf8("leStatus1"))
        self.tbLog1 = QtGui.QTextBrowser(self.tab)
        self.tbLog1.setGeometry(QtCore.QRect(12, 187, 227, 251))
        self.tbLog1.setObjectName(_fromUtf8("tbLog1"))
        self.pbLog1 = QtGui.QPushButton(self.tab)
        self.pbLog1.setGeometry(QtCore.QRect(188, 62, 51, 21))
        self.pbLog1.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);"))
        self.pbLog1.setObjectName(_fromUtf8("pbLog1"))
        self.lbMAC1 = QtGui.QLabel(self.tab)
        self.lbMAC1.setGeometry(QtCore.QRect(50, 63, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbMAC1.setFont(font)
        self.lbMAC1.setObjectName(_fromUtf8("lbMAC1"))
        self.tbLog1_2 = QtGui.QTextBrowser(self.tab)
        self.tbLog1_2.setGeometry(QtCore.QRect(256, 187, 227, 251))
        self.tbLog1_2.setObjectName(_fromUtf8("tbLog1_2"))
        self.textBrowser_6 = QtGui.QTextBrowser(self.tab)
        self.textBrowser_6.setEnabled(False)
        self.textBrowser_6.setGeometry(QtCore.QRect(254, 10, 231, 431))
        self.textBrowser_6.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.textBrowser_6.setObjectName(_fromUtf8("textBrowser_6"))
        self.lbMAC1_2 = QtGui.QLabel(self.tab)
        self.lbMAC1_2.setGeometry(QtCore.QRect(294, 63, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbMAC1_2.setFont(font)
        self.lbMAC1_2.setObjectName(_fromUtf8("lbMAC1_2"))
        self.leStatus1_2 = QtGui.QLineEdit(self.tab)
        self.leStatus1_2.setEnabled(True)
        self.leStatus1_2.setGeometry(QtCore.QRect(256, 84, 227, 102))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leStatus1_2.sizePolicy().hasHeightForWidth())
        self.leStatus1_2.setSizePolicy(sizePolicy)
        self.leStatus1_2.setMinimumSize(QtCore.QSize(60, 50))
        self.leStatus1_2.setMaximumSize(QtCore.QSize(9999999, 9999999))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bauhaus 93"))
        font.setPointSize(48)
        self.leStatus1_2.setFont(font)
        self.leStatus1_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.leStatus1_2.setMouseTracking(True)
        self.leStatus1_2.setAcceptDrops(True)
        self.leStatus1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leStatus1_2.setAutoFillBackground(False)
        self.leStatus1_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 0);"))
        self.leStatus1_2.setText(_fromUtf8("RUN"))
        self.leStatus1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.leStatus1_2.setReadOnly(True)
        self.leStatus1_2.setObjectName(_fromUtf8("leStatus1_2"))
        self.pbLog1_2 = QtGui.QPushButton(self.tab)
        self.pbLog1_2.setGeometry(QtCore.QRect(432, 62, 51, 21))
        self.pbLog1_2.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);"))
        self.pbLog1_2.setObjectName(_fromUtf8("pbLog1_2"))
        self.textBrowser_7 = QtGui.QTextBrowser(self.tab)
        self.textBrowser_7.setEnabled(True)
        self.textBrowser_7.setGeometry(QtCore.QRect(254, 10, 231, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_7.setFont(font)
        self.textBrowser_7.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);\n"
"color: rgb(85, 0, 0);"))
        self.textBrowser_7.setObjectName(_fromUtf8("textBrowser_7"))
        self.tbLog1_3 = QtGui.QTextBrowser(self.tab)
        self.tbLog1_3.setGeometry(QtCore.QRect(499, 187, 227, 251))
        self.tbLog1_3.setObjectName(_fromUtf8("tbLog1_3"))
        self.textBrowser_8 = QtGui.QTextBrowser(self.tab)
        self.textBrowser_8.setEnabled(False)
        self.textBrowser_8.setGeometry(QtCore.QRect(497, 10, 231, 431))
        self.textBrowser_8.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.textBrowser_8.setObjectName(_fromUtf8("textBrowser_8"))
        self.lbMAC1_3 = QtGui.QLabel(self.tab)
        self.lbMAC1_3.setGeometry(QtCore.QRect(537, 63, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbMAC1_3.setFont(font)
        self.lbMAC1_3.setObjectName(_fromUtf8("lbMAC1_3"))
        self.leStatus1_3 = QtGui.QLineEdit(self.tab)
        self.leStatus1_3.setEnabled(True)
        self.leStatus1_3.setGeometry(QtCore.QRect(499, 84, 227, 102))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leStatus1_3.sizePolicy().hasHeightForWidth())
        self.leStatus1_3.setSizePolicy(sizePolicy)
        self.leStatus1_3.setMinimumSize(QtCore.QSize(60, 50))
        self.leStatus1_3.setMaximumSize(QtCore.QSize(9999999, 9999999))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bauhaus 93"))
        font.setPointSize(48)
        self.leStatus1_3.setFont(font)
        self.leStatus1_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.leStatus1_3.setMouseTracking(True)
        self.leStatus1_3.setAcceptDrops(True)
        self.leStatus1_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leStatus1_3.setAutoFillBackground(False)
        self.leStatus1_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 0);"))
        self.leStatus1_3.setText(_fromUtf8("PASS"))
        self.leStatus1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.leStatus1_3.setReadOnly(True)
        self.leStatus1_3.setObjectName(_fromUtf8("leStatus1_3"))
        self.pbLog1_3 = QtGui.QPushButton(self.tab)
        self.pbLog1_3.setGeometry(QtCore.QRect(675, 62, 51, 21))
        self.pbLog1_3.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);"))
        self.pbLog1_3.setObjectName(_fromUtf8("pbLog1_3"))
        self.textBrowser_9 = QtGui.QTextBrowser(self.tab)
        self.textBrowser_9.setEnabled(True)
        self.textBrowser_9.setGeometry(QtCore.QRect(497, 10, 231, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_9.setFont(font)
        self.textBrowser_9.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);\n"
"color: rgb(85, 0, 0);"))
        self.textBrowser_9.setObjectName(_fromUtf8("textBrowser_9"))
        self.tbLog1_4 = QtGui.QTextBrowser(self.tab)
        self.tbLog1_4.setGeometry(QtCore.QRect(742, 187, 227, 251))
        self.tbLog1_4.setObjectName(_fromUtf8("tbLog1_4"))
        self.textBrowser_10 = QtGui.QTextBrowser(self.tab)
        self.textBrowser_10.setEnabled(False)
        self.textBrowser_10.setGeometry(QtCore.QRect(740, 10, 231, 431))
        self.textBrowser_10.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.textBrowser_10.setObjectName(_fromUtf8("textBrowser_10"))
        self.lbMAC1_4 = QtGui.QLabel(self.tab)
        self.lbMAC1_4.setGeometry(QtCore.QRect(780, 63, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbMAC1_4.setFont(font)
        self.lbMAC1_4.setObjectName(_fromUtf8("lbMAC1_4"))
        self.leStatus1_4 = QtGui.QLineEdit(self.tab)
        self.leStatus1_4.setEnabled(True)
        self.leStatus1_4.setGeometry(QtCore.QRect(742, 84, 227, 102))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leStatus1_4.sizePolicy().hasHeightForWidth())
        self.leStatus1_4.setSizePolicy(sizePolicy)
        self.leStatus1_4.setMinimumSize(QtCore.QSize(60, 50))
        self.leStatus1_4.setMaximumSize(QtCore.QSize(9999999, 9999999))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bauhaus 93"))
        font.setPointSize(48)
        self.leStatus1_4.setFont(font)
        self.leStatus1_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.leStatus1_4.setMouseTracking(True)
        self.leStatus1_4.setAcceptDrops(True)
        self.leStatus1_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leStatus1_4.setAutoFillBackground(False)
        self.leStatus1_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);"))
        self.leStatus1_4.setText(_fromUtf8("FAIL"))
        self.leStatus1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.leStatus1_4.setReadOnly(True)
        self.leStatus1_4.setObjectName(_fromUtf8("leStatus1_4"))
        self.pbLog1_4 = QtGui.QPushButton(self.tab)
        self.pbLog1_4.setGeometry(QtCore.QRect(918, 62, 51, 21))
        self.pbLog1_4.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);"))
        self.pbLog1_4.setObjectName(_fromUtf8("pbLog1_4"))
        self.textBrowser_11 = QtGui.QTextBrowser(self.tab)
        self.textBrowser_11.setEnabled(True)
        self.textBrowser_11.setGeometry(QtCore.QRect(740, 10, 231, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_11.setFont(font)
        self.textBrowser_11.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);\n"
"color: rgb(85, 0, 0);"))
        self.textBrowser_11.setObjectName(_fromUtf8("textBrowser_11"))
        self.twTestArea.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(500, 0, 481, 441))
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(16)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(230, 230, 230))
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.scrollArea = QtGui.QScrollArea(self.tab_2)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 501, 441))
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 439))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.textBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_20.setEnabled(True)
        self.textBrowser_20.setGeometry(QtCore.QRect(10, 10, 231, 101))
        self.textBrowser_20.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.textBrowser_20.setObjectName(_fromUtf8("textBrowser_20"))
        self.textBrowser_21 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_21.setEnabled(True)
        self.textBrowser_21.setGeometry(QtCore.QRect(10, 115, 231, 101))
        self.textBrowser_21.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.textBrowser_21.setObjectName(_fromUtf8("textBrowser_21"))
        self.textBrowser_22 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_22.setEnabled(True)
        self.textBrowser_22.setGeometry(QtCore.QRect(10, 220, 231, 101))
        self.textBrowser_22.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.textBrowser_22.setObjectName(_fromUtf8("textBrowser_22"))
        self.textBrowser_23 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_23.setEnabled(True)
        self.textBrowser_23.setGeometry(QtCore.QRect(10, 325, 231, 101))
        self.textBrowser_23.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.textBrowser_23.setObjectName(_fromUtf8("textBrowser_23"))
        self.textBrowser_24 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_24.setEnabled(True)
        self.textBrowser_24.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_24.setFont(font)
        self.textBrowser_24.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);\n"
"color: rgb(85, 0, 0);"))
        self.textBrowser_24.setObjectName(_fromUtf8("textBrowser_24"))
        self.textBrowser_25 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_25.setEnabled(True)
        self.textBrowser_25.setGeometry(QtCore.QRect(10, 115, 231, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_25.setFont(font)
        self.textBrowser_25.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);\n"
"color: rgb(85, 0, 0);"))
        self.textBrowser_25.setObjectName(_fromUtf8("textBrowser_25"))
        self.textBrowser_26 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_26.setEnabled(True)
        self.textBrowser_26.setGeometry(QtCore.QRect(10, 220, 231, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_26.setFont(font)
        self.textBrowser_26.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);\n"
"color: rgb(85, 0, 0);"))
        self.textBrowser_26.setObjectName(_fromUtf8("textBrowser_26"))
        self.textBrowser_27 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_27.setEnabled(True)
        self.textBrowser_27.setGeometry(QtCore.QRect(10, 325, 231, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_27.setFont(font)
        self.textBrowser_27.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);\n"
"color: rgb(85, 0, 0);"))
        self.textBrowser_27.setObjectName(_fromUtf8("textBrowser_27"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 71, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.leCOM = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.leCOM.setGeometry(QtCore.QRect(50, 80, 51, 21))
        self.leCOM.setMaxLength(10)
        self.leCOM.setObjectName(_fromUtf8("leCOM"))
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(20, 41, 41, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cbComIndex = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComIndex.setGeometry(QtCore.QRect(50, 50, 71, 21))
        self.cbComIndex.setObjectName(_fromUtf8("cbComIndex"))
        self.cbComIndex.addItem(_fromUtf8(""))
        self.cbComBaud = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComBaud.setGeometry(QtCore.QRect(50, 80, 71, 21))
        self.cbComBaud.setObjectName(_fromUtf8("cbComBaud"))
        self.cbComBaud.addItem(_fromUtf8(""))
        self.cbComBaud.addItem(_fromUtf8(""))
        self.cbComBaud.addItem(_fromUtf8(""))
        self.cbComBaud.addItem(_fromUtf8(""))
        self.cbComBaud.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(130, 42, 41, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(130, 70, 71, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.leCOM_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.leCOM_2.setGeometry(QtCore.QRect(160, 80, 51, 21))
        self.leCOM_2.setMaxLength(10)
        self.leCOM_2.setObjectName(_fromUtf8("leCOM_2"))
        self.cbComIndex_2 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComIndex_2.setGeometry(QtCore.QRect(160, 50, 71, 21))
        self.cbComIndex_2.setObjectName(_fromUtf8("cbComIndex_2"))
        self.cbComIndex_2.addItem(_fromUtf8(""))
        self.cbComBaud_2 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComBaud_2.setGeometry(QtCore.QRect(160, 80, 71, 21))
        self.cbComBaud_2.setObjectName(_fromUtf8("cbComBaud_2"))
        self.cbComBaud_2.addItem(_fromUtf8(""))
        self.cbComBaud_2.addItem(_fromUtf8(""))
        self.cbComBaud_2.addItem(_fromUtf8(""))
        self.cbComBaud_2.addItem(_fromUtf8(""))
        self.cbComBaud_2.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(130, 147, 41, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cbComIndex_3 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComIndex_3.setGeometry(QtCore.QRect(160, 155, 71, 21))
        self.cbComIndex_3.setObjectName(_fromUtf8("cbComIndex_3"))
        self.cbComIndex_3.addItem(_fromUtf8(""))
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(20, 175, 71, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(20, 146, 41, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.leCOM_3 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.leCOM_3.setGeometry(QtCore.QRect(160, 185, 51, 21))
        self.leCOM_3.setMaxLength(10)
        self.leCOM_3.setObjectName(_fromUtf8("leCOM_3"))
        self.leCOM_4 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.leCOM_4.setGeometry(QtCore.QRect(50, 185, 51, 21))
        self.leCOM_4.setMaxLength(10)
        self.leCOM_4.setObjectName(_fromUtf8("leCOM_4"))
        self.cbComBaud_3 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComBaud_3.setGeometry(QtCore.QRect(160, 185, 71, 21))
        self.cbComBaud_3.setObjectName(_fromUtf8("cbComBaud_3"))
        self.cbComBaud_3.addItem(_fromUtf8(""))
        self.cbComBaud_3.addItem(_fromUtf8(""))
        self.cbComBaud_3.addItem(_fromUtf8(""))
        self.cbComBaud_3.addItem(_fromUtf8(""))
        self.cbComBaud_3.addItem(_fromUtf8(""))
        self.cbComIndex_4 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComIndex_4.setGeometry(QtCore.QRect(50, 155, 71, 21))
        self.cbComIndex_4.setObjectName(_fromUtf8("cbComIndex_4"))
        self.cbComIndex_4.addItem(_fromUtf8(""))
        self.cbComBaud_4 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComBaud_4.setGeometry(QtCore.QRect(50, 185, 71, 21))
        self.cbComBaud_4.setObjectName(_fromUtf8("cbComBaud_4"))
        self.cbComBaud_4.addItem(_fromUtf8(""))
        self.cbComBaud_4.addItem(_fromUtf8(""))
        self.cbComBaud_4.addItem(_fromUtf8(""))
        self.cbComBaud_4.addItem(_fromUtf8(""))
        self.cbComBaud_4.addItem(_fromUtf8(""))
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(130, 175, 71, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(130, 252, 41, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.cbComIndex_5 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComIndex_5.setGeometry(QtCore.QRect(160, 260, 71, 21))
        self.cbComIndex_5.setObjectName(_fromUtf8("cbComIndex_5"))
        self.cbComIndex_5.addItem(_fromUtf8(""))
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(20, 280, 71, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(20, 251, 41, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.leCOM_5 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.leCOM_5.setGeometry(QtCore.QRect(160, 290, 51, 21))
        self.leCOM_5.setMaxLength(10)
        self.leCOM_5.setObjectName(_fromUtf8("leCOM_5"))
        self.leCOM_6 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.leCOM_6.setGeometry(QtCore.QRect(50, 290, 51, 21))
        self.leCOM_6.setMaxLength(10)
        self.leCOM_6.setObjectName(_fromUtf8("leCOM_6"))
        self.cbComBaud_5 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComBaud_5.setGeometry(QtCore.QRect(160, 290, 71, 21))
        self.cbComBaud_5.setObjectName(_fromUtf8("cbComBaud_5"))
        self.cbComBaud_5.addItem(_fromUtf8(""))
        self.cbComBaud_5.addItem(_fromUtf8(""))
        self.cbComBaud_5.addItem(_fromUtf8(""))
        self.cbComBaud_5.addItem(_fromUtf8(""))
        self.cbComBaud_5.addItem(_fromUtf8(""))
        self.cbComIndex_6 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComIndex_6.setGeometry(QtCore.QRect(50, 260, 71, 21))
        self.cbComIndex_6.setObjectName(_fromUtf8("cbComIndex_6"))
        self.cbComIndex_6.addItem(_fromUtf8(""))
        self.cbComBaud_6 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComBaud_6.setGeometry(QtCore.QRect(50, 290, 71, 21))
        self.cbComBaud_6.setObjectName(_fromUtf8("cbComBaud_6"))
        self.cbComBaud_6.addItem(_fromUtf8(""))
        self.cbComBaud_6.addItem(_fromUtf8(""))
        self.cbComBaud_6.addItem(_fromUtf8(""))
        self.cbComBaud_6.addItem(_fromUtf8(""))
        self.cbComBaud_6.addItem(_fromUtf8(""))
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setGeometry(QtCore.QRect(130, 280, 71, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setGeometry(QtCore.QRect(130, 357, 41, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.cbComIndex_7 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComIndex_7.setGeometry(QtCore.QRect(160, 365, 71, 21))
        self.cbComIndex_7.setObjectName(_fromUtf8("cbComIndex_7"))
        self.cbComIndex_7.addItem(_fromUtf8(""))
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setGeometry(QtCore.QRect(20, 385, 71, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setGeometry(QtCore.QRect(20, 356, 41, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.leCOM_7 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.leCOM_7.setGeometry(QtCore.QRect(160, 395, 51, 21))
        self.leCOM_7.setMaxLength(10)
        self.leCOM_7.setObjectName(_fromUtf8("leCOM_7"))
        self.leCOM_8 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.leCOM_8.setGeometry(QtCore.QRect(50, 395, 51, 21))
        self.leCOM_8.setMaxLength(10)
        self.leCOM_8.setObjectName(_fromUtf8("leCOM_8"))
        self.cbComBaud_7 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComBaud_7.setGeometry(QtCore.QRect(160, 395, 71, 21))
        self.cbComBaud_7.setObjectName(_fromUtf8("cbComBaud_7"))
        self.cbComBaud_7.addItem(_fromUtf8(""))
        self.cbComBaud_7.addItem(_fromUtf8(""))
        self.cbComBaud_7.addItem(_fromUtf8(""))
        self.cbComBaud_7.addItem(_fromUtf8(""))
        self.cbComBaud_7.addItem(_fromUtf8(""))
        self.cbComIndex_8 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComIndex_8.setGeometry(QtCore.QRect(50, 365, 71, 21))
        self.cbComIndex_8.setObjectName(_fromUtf8("cbComIndex_8"))
        self.cbComIndex_8.addItem(_fromUtf8(""))
        self.cbComBaud_8 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cbComBaud_8.setGeometry(QtCore.QRect(50, 395, 71, 21))
        self.cbComBaud_8.setObjectName(_fromUtf8("cbComBaud_8"))
        self.cbComBaud_8.addItem(_fromUtf8(""))
        self.cbComBaud_8.addItem(_fromUtf8(""))
        self.cbComBaud_8.addItem(_fromUtf8(""))
        self.cbComBaud_8.addItem(_fromUtf8(""))
        self.cbComBaud_8.addItem(_fromUtf8(""))
        self.label_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setGeometry(QtCore.QRect(130, 385, 71, 39))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.twTestArea.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.trwTestFlow = QtGui.QTreeWidget(self.tab_4)
        self.trwTestFlow.setGeometry(QtCore.QRect(-1, -1, 831, 448))
        self.trwTestFlow.setObjectName(_fromUtf8("trwTestFlow"))
        item_0 = QtGui.QTreeWidgetItem(self.trwTestFlow)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtGui.QTreeWidgetItem(self.trwTestFlow)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        item_4.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        item_4.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        item_4.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        item_4.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtGui.QTreeWidgetItem(self.trwTestFlow)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_4 = QtGui.QTreeWidgetItem(item_3)
        item_4.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        self.pbSubmit = QtGui.QPushButton(self.tab_4)
        self.pbSubmit.setGeometry(QtCore.QRect(840, 390, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pbSubmit.setFont(font)
        self.pbSubmit.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);"))
        self.pbSubmit.setObjectName(_fromUtf8("pbSubmit"))
        self.pbReset = QtGui.QPushButton(self.tab_4)
        self.pbReset.setGeometry(QtCore.QRect(840, 340, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pbReset.setFont(font)
        self.pbReset.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);"))
        self.pbReset.setObjectName(_fromUtf8("pbReset"))
        self.twTestArea.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tableWidget_5 = QtGui.QTableWidget(self.tab_5)
        self.tableWidget_5.setGeometry(QtCore.QRect(-1, -1, 986, 448))
        self.tableWidget_5.setAutoFillBackground(True)
        self.tableWidget_5.setShowGrid(True)
        self.tableWidget_5.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_5.setWordWrap(True)
        self.tableWidget_5.setCornerButtonEnabled(True)
        self.tableWidget_5.setObjectName(_fromUtf8("tableWidget_5"))
        self.tableWidget_5.setColumnCount(6)
        self.tableWidget_5.setRowCount(9)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        self.twTestArea.addTab(self.tab_5, _fromUtf8(""))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(250, 0, 3, 165))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(625, 2, 3, 163))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 0, 1000, 3))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(252, 2, 371, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet(_fromUtf8("font: 14pt \"Arial\";"))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(627, 2, 371, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet(_fromUtf8("font: 12pt \"Comic Sans MS\";"))
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(2, 132, 246, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 127);\n"
"border-color: rgb(0, 255, 255);"))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 10, 281, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 10, 271, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lbModuleType = QtGui.QLabel(self.centralwidget)
        self.lbModuleType.setGeometry(QtCore.QRect(369, 43, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        self.lbModuleType.setFont(font)
        self.lbModuleType.setObjectName(_fromUtf8("lbModuleType"))
        self.lbFWVer = QtGui.QLabel(self.centralwidget)
        self.lbFWVer.setGeometry(QtCore.QRect(369, 65, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        self.lbFWVer.setFont(font)
        self.lbFWVer.setObjectName(_fromUtf8("lbFWVer"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(369, 90, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lbMPN = QtGui.QLabel(self.centralwidget)
        self.lbMPN.setGeometry(QtCore.QRect(369, 112, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        self.lbMPN.setFont(font)
        self.lbMPN.setObjectName(_fromUtf8("lbMPN"))
        self.lbStatus = QtGui.QLabel(self.centralwidget)
        self.lbStatus.setGeometry(QtCore.QRect(369, 134, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        self.lbStatus.setFont(font)
        self.lbStatus.setObjectName(_fromUtf8("lbStatus"))
        self.lbPlanID = QtGui.QLabel(self.centralwidget)
        self.lbPlanID.setGeometry(QtCore.QRect(750, 112, 221, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        self.lbPlanID.setFont(font)
        self.lbPlanID.setObjectName(_fromUtf8("lbPlanID"))
        self.lbBatchSid = QtGui.QLabel(self.centralwidget)
        self.lbBatchSid.setGeometry(QtCore.QRect(750, 89, 221, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        self.lbBatchSid.setFont(font)
        self.lbBatchSid.setObjectName(_fromUtf8("lbBatchSid"))
        self.lbFacID = QtGui.QLabel(self.centralwidget)
        self.lbFacID.setGeometry(QtCore.QRect(750, 66, 221, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        self.lbFacID.setFont(font)
        self.lbFacID.setObjectName(_fromUtf8("lbFacID"))
        self.lbWorkStat = QtGui.QLabel(self.centralwidget)
        self.lbWorkStat.setGeometry(QtCore.QRect(750, 135, 191, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Rounded MT Bold"))
        font.setPointSize(12)
        self.lbWorkStat.setFont(font)
        self.lbWorkStat.setObjectName(_fromUtf8("lbWorkStat"))
        self.lbServerStat = QtGui.QLabel(self.centralwidget)
        self.lbServerStat.setGeometry(QtCore.QRect(90, 137, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.lbServerStat.setFont(font)
        self.lbServerStat.setObjectName(_fromUtf8("lbServerStat"))
        self.fraLogo = QtGui.QFrame(self.centralwidget)
        self.fraLogo.setGeometry(QtCore.QRect(2, 2, 246, 128))
        self.fraLogo.setAutoFillBackground(False)
        self.fraLogo.setStyleSheet(_fromUtf8("background-image: url(:/images/logo_m.jpg);"))
        self.fraLogo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraLogo.setFrameShadow(QtGui.QFrame.Raised)
        self.fraLogo.setObjectName(_fromUtf8("fraLogo"))
        self.pbStart = QtGui.QPushButton(self.centralwidget)
        self.pbStart.setGeometry(QtCore.QRect(60, 70, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pbStart.setFont(font)
        self.pbStart.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 200, 200);"))
        self.pbStart.setObjectName(_fromUtf8("pbStart"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.twTestArea.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">MAC:</span></p></body></html>", None))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">DUT1</span></p></body></html>", None))
        self.pbLog1.setText(_translate("MainWindow", "log", None))
        self.lbMAC1.setText(_translate("MainWindow", "2c3ae8080000", None))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">MAC:</span></p></body></html>", None))
        self.lbMAC1_2.setText(_translate("MainWindow", "2c3ae8080000", None))
        self.pbLog1_2.setText(_translate("MainWindow", "log", None))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">DUT2</span></p></body></html>", None))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">MAC:</span></p></body></html>", None))
        self.lbMAC1_3.setText(_translate("MainWindow", "2c3ae8080000", None))
        self.pbLog1_3.setText(_translate("MainWindow", "log", None))
        self.textBrowser_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">DUT3</span></p></body></html>", None))
        self.textBrowser_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">MAC:</span></p></body></html>", None))
        self.lbMAC1_4.setText(_translate("MainWindow", "2c3ae8080000", None))
        self.pbLog1_4.setText(_translate("MainWindow", "log", None))
        self.textBrowser_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">DUT4</span></p></body></html>", None))
        self.twTestArea.setTabText(self.twTestArea.indexOf(self.tab), _translate("MainWindow", "Status", None))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "DUT1_PORT1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "DUT1_RATE1", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "DUT1_PORT2", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "DUT1_RATE2", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "DUT2_PORT1", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "DUT2_RATE1", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "DUT2_PORT2", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "DUT2_RATE2", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "DUT3_PORT1", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "DUT3_RATE1", None))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "DUT3_PORT2", None))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "DUT3_RATE2", None))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "DUT4_PORT1", None))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "DUT4_RATE1", None))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "DUT4_PORT2", None))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "DUT4_RATE2", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Descrip", None))
        self.textBrowser_20.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.textBrowser_21.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Black\'; font-size:10pt; font-weight:600;\">DUT2</span></p></body></html>", None))
        self.textBrowser_22.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.textBrowser_23.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.textBrowser_24.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">DUT1</span></p></body></html>", None))
        self.textBrowser_25.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">DUT2</span></p></body></html>", None))
        self.textBrowser_26.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">DUT3</span></p></body></html>", None))
        self.textBrowser_27.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">DUT4</span></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "Rate1", None))
        self.label_4.setText(_translate("MainWindow", "PORT1", None))
        self.cbComIndex.setItemText(0, _translate("MainWindow", "--", None))
        self.cbComBaud.setItemText(0, _translate("MainWindow", "9600", None))
        self.cbComBaud.setItemText(1, _translate("MainWindow", "74880", None))
        self.cbComBaud.setItemText(2, _translate("MainWindow", "115200", None))
        self.cbComBaud.setItemText(3, _translate("MainWindow", "921600", None))
        self.cbComBaud.setItemText(4, _translate("MainWindow", "custom", None))
        self.label_6.setText(_translate("MainWindow", "PORT2", None))
        self.label_7.setText(_translate("MainWindow", "Rate2", None))
        self.cbComIndex_2.setItemText(0, _translate("MainWindow", "--", None))
        self.cbComBaud_2.setItemText(0, _translate("MainWindow", "9600", None))
        self.cbComBaud_2.setItemText(1, _translate("MainWindow", "74880", None))
        self.cbComBaud_2.setItemText(2, _translate("MainWindow", "115200", None))
        self.cbComBaud_2.setItemText(3, _translate("MainWindow", "921600", None))
        self.cbComBaud_2.setItemText(4, _translate("MainWindow", "custom", None))
        self.label_8.setText(_translate("MainWindow", "PORT2", None))
        self.cbComIndex_3.setItemText(0, _translate("MainWindow", "--", None))
        self.label_9.setText(_translate("MainWindow", "Rate1", None))
        self.label_10.setText(_translate("MainWindow", "PORT1", None))
        self.cbComBaud_3.setItemText(0, _translate("MainWindow", "9600", None))
        self.cbComBaud_3.setItemText(1, _translate("MainWindow", "74880", None))
        self.cbComBaud_3.setItemText(2, _translate("MainWindow", "115200", None))
        self.cbComBaud_3.setItemText(3, _translate("MainWindow", "921600", None))
        self.cbComBaud_3.setItemText(4, _translate("MainWindow", "custom", None))
        self.cbComIndex_4.setItemText(0, _translate("MainWindow", "--", None))
        self.cbComBaud_4.setItemText(0, _translate("MainWindow", "9600", None))
        self.cbComBaud_4.setItemText(1, _translate("MainWindow", "74880", None))
        self.cbComBaud_4.setItemText(2, _translate("MainWindow", "115200", None))
        self.cbComBaud_4.setItemText(3, _translate("MainWindow", "921600", None))
        self.cbComBaud_4.setItemText(4, _translate("MainWindow", "custom", None))
        self.label_11.setText(_translate("MainWindow", "Rate2", None))
        self.label_12.setText(_translate("MainWindow", "PORT2", None))
        self.cbComIndex_5.setItemText(0, _translate("MainWindow", "--", None))
        self.label_13.setText(_translate("MainWindow", "Rate1", None))
        self.label_14.setText(_translate("MainWindow", "PORT1", None))
        self.cbComBaud_5.setItemText(0, _translate("MainWindow", "9600", None))
        self.cbComBaud_5.setItemText(1, _translate("MainWindow", "74880", None))
        self.cbComBaud_5.setItemText(2, _translate("MainWindow", "115200", None))
        self.cbComBaud_5.setItemText(3, _translate("MainWindow", "921600", None))
        self.cbComBaud_5.setItemText(4, _translate("MainWindow", "custom", None))
        self.cbComIndex_6.setItemText(0, _translate("MainWindow", "--", None))
        self.cbComBaud_6.setItemText(0, _translate("MainWindow", "9600", None))
        self.cbComBaud_6.setItemText(1, _translate("MainWindow", "74880", None))
        self.cbComBaud_6.setItemText(2, _translate("MainWindow", "115200", None))
        self.cbComBaud_6.setItemText(3, _translate("MainWindow", "921600", None))
        self.cbComBaud_6.setItemText(4, _translate("MainWindow", "custom", None))
        self.label_15.setText(_translate("MainWindow", "Rate2", None))
        self.label_16.setText(_translate("MainWindow", "PORT2", None))
        self.cbComIndex_7.setItemText(0, _translate("MainWindow", "--", None))
        self.label_17.setText(_translate("MainWindow", "Rate1", None))
        self.label_18.setText(_translate("MainWindow", "PORT1", None))
        self.cbComBaud_7.setItemText(0, _translate("MainWindow", "9600", None))
        self.cbComBaud_7.setItemText(1, _translate("MainWindow", "74880", None))
        self.cbComBaud_7.setItemText(2, _translate("MainWindow", "115200", None))
        self.cbComBaud_7.setItemText(3, _translate("MainWindow", "921600", None))
        self.cbComBaud_7.setItemText(4, _translate("MainWindow", "custom", None))
        self.cbComIndex_8.setItemText(0, _translate("MainWindow", "--", None))
        self.cbComBaud_8.setItemText(0, _translate("MainWindow", "9600", None))
        self.cbComBaud_8.setItemText(1, _translate("MainWindow", "74880", None))
        self.cbComBaud_8.setItemText(2, _translate("MainWindow", "115200", None))
        self.cbComBaud_8.setItemText(3, _translate("MainWindow", "921600", None))
        self.cbComBaud_8.setItemText(4, _translate("MainWindow", "custom", None))
        self.label_19.setText(_translate("MainWindow", "Rate2", None))
        self.twTestArea.setTabText(self.twTestArea.indexOf(self.tab_2), _translate("MainWindow", "Dut Config", None))
        self.trwTestFlow.headerItem().setText(0, _translate("MainWindow", "Total", None))
        __sortingEnabled = self.trwTestFlow.isSortingEnabled()
        self.trwTestFlow.setSortingEnabled(False)
        self.trwTestFlow.topLevelItem(0).setText(0, _translate("MainWindow", "RF", None))
        self.trwTestFlow.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "TX", None))
        self.trwTestFlow.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "RX", None))
        self.trwTestFlow.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "ANALOG", None))
        self.trwTestFlow.topLevelItem(1).setText(0, _translate("MainWindow", "GENERAL_TEST", None))
        self.trwTestFlow.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "USER_FW_CKECK", None))
        self.trwTestFlow.topLevelItem(1).child(0).child(0).setText(0, _translate("MainWindow", "USER_FW_VER_TEST", None))
        self.trwTestFlow.topLevelItem(1).child(0).child(0).child(0).setText(0, _translate("MainWindow", "USER_FW_VER_BAUD", None))
        self.trwTestFlow.topLevelItem(1).child(0).child(0).child(0).child(0).setText(0, _translate("MainWindow", "115200", None))
        self.trwTestFlow.topLevelItem(1).child(0).child(0).child(1).setText(0, _translate("MainWindow", "USER_FW_VER_STR", None))
        self.trwTestFlow.topLevelItem(1).child(0).child(0).child(1).child(0).setText(0, _translate("MainWindow", "ver_1.0.0", None))
        self.trwTestFlow.topLevelItem(1).child(0).child(0).child(2).setText(0, _translate("MainWindow", "USER_FW_VER_TIMEOUT(s)", None))
        self.trwTestFlow.topLevelItem(1).child(0).child(0).child(2).child(0).setText(0, _translate("MainWindow", "3", None))
        self.trwTestFlow.topLevelItem(1).child(0).child(0).child(3).setText(0, _translate("MainWindow", "USER_FW_VER_DELAY(s)", None))
        self.trwTestFlow.topLevelItem(1).child(0).child(0).child(3).child(0).setText(0, _translate("MainWindow", "0", None))
        self.trwTestFlow.topLevelItem(1).child(0).child(1).setText(0, _translate("MainWindow", "USER_TEST_CMD<cmd,rsp,tmo>", None))
        self.trwTestFlow.topLevelItem(1).child(0).child(1).child(0).setText(0, _translate("MainWindow", "<AT+GMR,\"1.0.b1.0\",5>;<AT+CWLAP,\"OK\",5>", None))
        self.trwTestFlow.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "GPIO_8266_TEST", None))
        self.trwTestFlow.topLevelItem(1).child(1).child(0).setText(0, _translate("MainWindow", "GPIO_8266_TEST_PIN", None))
        self.trwTestFlow.topLevelItem(1).child(1).child(0).child(0).setText(0, _translate("MainWindow", "0x3030", None))
        self.trwTestFlow.topLevelItem(1).child(1).child(1).setText(0, _translate("MainWindow", "GPIO_8266_TEST_VAL", None))
        self.trwTestFlow.topLevelItem(1).child(1).child(1).child(0).setText(0, _translate("MainWindow", "0x1010", None))
        self.trwTestFlow.topLevelItem(1).child(1).child(2).setText(0, _translate("MainWindow", "GPIO_8266_TEST_READ_EN", None))
        self.trwTestFlow.topLevelItem(1).child(1).child(2).child(0).setText(0, _translate("MainWindow", "0", None))
        self.trwTestFlow.topLevelItem(1).child(1).child(3).setText(0, _translate("MainWindow", "GPIO_8266_TEST_VAL_TARGET", None))
        self.trwTestFlow.topLevelItem(1).child(1).child(3).child(0).setText(0, _translate("MainWindow", "0x3030", None))
        self.trwTestFlow.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "GPIO_32_TEST", None))
        self.trwTestFlow.topLevelItem(1).child(2).child(0).setText(0, _translate("MainWindow", "GPIO_32_TEST_VAL_0", None))
        self.trwTestFlow.topLevelItem(1).child(2).child(0).child(0).setText(0, _translate("MainWindow", "0xD9000C20", None))
        self.trwTestFlow.topLevelItem(1).child(2).child(1).setText(0, _translate("MainWindow", "GPIO_32_TEST_VAL_1", None))
        self.trwTestFlow.topLevelItem(1).child(2).child(1).child(0).setText(0, _translate("MainWindow", "0x0054E0E0", None))
        self.trwTestFlow.topLevelItem(1).child(2).child(2).setText(0, _translate("MainWindow", "GPIO_32_TEST_VAL_2", None))
        self.trwTestFlow.topLevelItem(1).child(2).child(2).child(0).setText(0, _translate("MainWindow", "0x00000055", None))
        self.trwTestFlow.topLevelItem(1).child(2).child(3).setText(0, _translate("MainWindow", "GPIO_32_TEST_TARGET_0", None))
        self.trwTestFlow.topLevelItem(1).child(2).child(3).child(0).setText(0, _translate("MainWindow", "0x33000000", None))
        self.trwTestFlow.topLevelItem(1).child(2).child(4).setText(0, _translate("MainWindow", "GPIO_32_TEST_TARGET_1", None))
        self.trwTestFlow.topLevelItem(1).child(2).child(4).child(0).setText(0, _translate("MainWindow", "0x00AC0000", None))
        self.trwTestFlow.topLevelItem(1).child(2).child(5).setText(0, _translate("MainWindow", "GPIO_32_TEST_TARGET_2", None))
        self.trwTestFlow.topLevelItem(1).child(2).child(5).child(0).setText(0, _translate("MainWindow", "0x000000BB", None))
        self.trwTestFlow.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "FLASH_ID_CHECK", None))
        self.trwTestFlow.topLevelItem(1).child(4).setText(0, _translate("MainWindow", "FLASH_RW_CHECK", None))
        self.trwTestFlow.topLevelItem(1).child(5).setText(0, _translate("MainWindow", "ADC_TEST", None))
        self.trwTestFlow.topLevelItem(1).child(6).setText(0, _translate("MainWindow", "PSRAMTEST", None))
        self.trwTestFlow.topLevelItem(1).child(7).setText(0, _translate("MainWindow", "PVTTEST", None))
        self.trwTestFlow.topLevelItem(2).setText(0, _translate("MainWindow", "FUNCTION", None))
        self.trwTestFlow.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "USER_FW_DOWNLOAD", None))
        self.trwTestFlow.topLevelItem(2).child(0).child(0).setText(0, _translate("MainWindow", "USER_FW_DOWNLOAD_PORT", None))
        self.trwTestFlow.topLevelItem(2).child(0).child(0).child(0).setText(0, _translate("MainWindow", "SPI", None))
        self.trwTestFlow.topLevelItem(2).child(0).child(1).setText(0, _translate("MainWindow", "USER_FW_FORCE_DOWNLOAD", None))
        self.trwTestFlow.topLevelItem(2).child(0).child(1).child(0).setText(0, _translate("MainWindow", "bin_pairs<path,addr>", None))
        self.trwTestFlow.topLevelItem(2).child(0).child(1).child(0).child(0).setText(0, _translate("MainWindow", "<./image/blank.bin,0xfc000>;<./bin/test.bin,0x0>", None))
        self.trwTestFlow.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "CUSTOM_MAC", None))
        self.trwTestFlow.topLevelItem(2).child(1).child(0).setText(0, _translate("MainWindow", "CUS_MAC_ADDR", None))
        self.trwTestFlow.topLevelItem(2).child(1).child(0).child(0).setText(0, _translate("MainWindow", "0x79000", None))
        self.trwTestFlow.topLevelItem(2).child(1).child(1).setText(0, _translate("MainWindow", "MAC_FILE_PATH", None))
        self.trwTestFlow.topLevelItem(2).child(1).child(1).child(0).setText(0, _translate("MainWindow", "/config/mac.csv", None))
        self.trwTestFlow.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "FLASH_CMD_TEST", None))
        self.trwTestFlow.topLevelItem(2).child(2).child(0).setText(0, _translate("MainWindow", "ESP32_FLASH_80M_TEST_CMD", None))
        self.trwTestFlow.topLevelItem(2).child(2).child(0).child(0).setText(0, _translate("MainWindow", "flash_op 0x0 0x5aff00a5 16 0 1 6 5 3 3 1", None))
        self.trwTestFlow.topLevelItem(2).child(2).child(1).setText(0, _translate("MainWindow", "ESP32_FLASH_PASS_FREQ_MHZ", None))
        self.trwTestFlow.topLevelItem(2).child(2).child(1).child(0).setText(0, _translate("MainWindow", "88", None))
        self.trwTestFlow.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "ESP32_ADC_REF_CAL", None))
        self.trwTestFlow.setSortingEnabled(__sortingEnabled)
        self.pbSubmit.setText(_translate("MainWindow", "SUBMIT", None))
        self.pbReset.setText(_translate("MainWindow", "RESET", None))
        self.twTestArea.setTabText(self.twTestArea.indexOf(self.tab_4), _translate("MainWindow", "Test flow", None))
        self.tableWidget_5.setSortingEnabled(False)
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_5.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_5.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_5.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_5.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_5.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_5.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tableWidget_5.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CASES", None))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "attion1", None))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Item1", None))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Item2", None))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Item4", None))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Descrip", None))
        self.twTestArea.setTabText(self.twTestArea.indexOf(self.tab_5), _translate("MainWindow", " Spec ", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Narrow\'; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Narrow\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\';\">Module Type  :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\';\">Firmware Ver :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\';\">PO No        :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\';\">MPN No         :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\';\">Total Status    :</span></p></body></html>", None))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans MS\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Narrow\'; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Narrow\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\'; font-size:14pt;\">Server address:  </span><span style=\" font-family:\'Arial Narrow\'; font-size:14pt; font-weight:600;\">factory.espressif.com</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\'; font-size:14pt;\">Factory ID         :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\'; font-size:14pt;\">Batch ID            :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\'; font-size:14pt;\">Fac-Plan ID      :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\'; font-size:14pt;\">Loacl Status     :</span></p></body></html>", None))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Narrow\'; font-weight:600;\">Position : </span></p></body></html>", None))
        self.label.setText(_translate("MainWindow", "Overall production state", None))
        self.label_2.setText(_translate("MainWindow", "Local production state", None))
        self.lbModuleType.setText(_translate("MainWindow", "WROOM02", None))
        self.lbFWVer.setText(_translate("MainWindow", "Ver_1.0.0", None))
        self.label_5.setText(_translate("MainWindow", "c0392", None))
        self.lbMPN.setText(_translate("MainWindow", "hehe", None))
        self.lbStatus.setText(_translate("MainWindow", "WORKING", None))
        self.lbPlanID.setText(_translate("MainWindow", "XXXX", None))
        self.lbBatchSid.setText(_translate("MainWindow", "XXXX", None))
        self.lbFacID.setText(_translate("MainWindow", "XXXX", None))
        self.lbWorkStat.setText(_translate("MainWindow", "xx/xxx", None))
        self.lbServerStat.setText(_translate("MainWindow", "Local/Cloud", None))
        self.pbStart.setText(_translate("MainWindow", "START", None))
        self.menu.setTitle(_translate("MainWindow", "File", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

