# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpioTestConfigUI.ui'
#
# Created: Tue Jan 16 17:15:44 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_gpioConfigTool(object):
    def setupUi(self, gpioConfigTool):
        gpioConfigTool.setObjectName(_fromUtf8("gpioConfigTool"))
        gpioConfigTool.resize(754, 500)
        gpioConfigTool.setMinimumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtGui.QWidget(gpioConfigTool)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pbIO0 = MyPushButton(self.centralwidget)
        self.pbIO0.setGeometry(QtCore.QRect(90, 55, 31, 41))
        self.pbIO0.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO0.setCheckable(False)
        self.pbIO0.setObjectName(_fromUtf8("pbIO0"))
        self.buttonGroup = QtGui.QButtonGroup(gpioConfigTool)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.pbIO0)
        self.pbIO1 = MyPushButton(self.centralwidget)
        self.pbIO1.setGeometry(QtCore.QRect(120, 55, 31, 41))
        self.pbIO1.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO1.setObjectName(_fromUtf8("pbIO1"))
        self.buttonGroup.addButton(self.pbIO1)
        self.pbIO2 = MyPushButton(self.centralwidget)
        self.pbIO2.setGeometry(QtCore.QRect(150, 55, 31, 41))
        self.pbIO2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO2.setObjectName(_fromUtf8("pbIO2"))
        self.buttonGroup.addButton(self.pbIO2)
        self.pbIO3 = MyPushButton(self.centralwidget)
        self.pbIO3.setGeometry(QtCore.QRect(180, 55, 31, 41))
        self.pbIO3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO3.setObjectName(_fromUtf8("pbIO3"))
        self.buttonGroup.addButton(self.pbIO3)
        self.pbIO4 = MyPushButton(self.centralwidget)
        self.pbIO4.setGeometry(QtCore.QRect(210, 55, 31, 41))
        self.pbIO4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO4.setObjectName(_fromUtf8("pbIO4"))
        self.buttonGroup.addButton(self.pbIO4)
        self.pbIO5 = MyPushButton(self.centralwidget)
        self.pbIO5.setGeometry(QtCore.QRect(240, 55, 31, 41))
        self.pbIO5.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO5.setObjectName(_fromUtf8("pbIO5"))
        self.buttonGroup.addButton(self.pbIO5)
        self.pbIO6 = MyPushButton(self.centralwidget)
        self.pbIO6.setGeometry(QtCore.QRect(270, 55, 31, 41))
        self.pbIO6.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO6.setObjectName(_fromUtf8("pbIO6"))
        self.buttonGroup.addButton(self.pbIO6)
        self.pbIO7 = MyPushButton(self.centralwidget)
        self.pbIO7.setGeometry(QtCore.QRect(300, 55, 31, 41))
        self.pbIO7.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO7.setObjectName(_fromUtf8("pbIO7"))
        self.buttonGroup.addButton(self.pbIO7)
        self.pbIO8 = MyPushButton(self.centralwidget)
        self.pbIO8.setGeometry(QtCore.QRect(330, 55, 31, 41))
        self.pbIO8.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO8.setObjectName(_fromUtf8("pbIO8"))
        self.buttonGroup.addButton(self.pbIO8)
        self.pbIO9 = MyPushButton(self.centralwidget)
        self.pbIO9.setGeometry(QtCore.QRect(360, 55, 31, 41))
        self.pbIO9.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO9.setObjectName(_fromUtf8("pbIO9"))
        self.buttonGroup.addButton(self.pbIO9)
        self.pbIO10 = MyPushButton(self.centralwidget)
        self.pbIO10.setGeometry(QtCore.QRect(390, 100, 51, 31))
        self.pbIO10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO10.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(200, 200, 200);"))
        self.pbIO10.setObjectName(_fromUtf8("pbIO10"))
        self.buttonGroup.addButton(self.pbIO10)
        self.pbIO11 = MyPushButton(self.centralwidget)
        self.pbIO11.setGeometry(QtCore.QRect(390, 130, 51, 31))
        self.pbIO11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO11.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(200, 200, 200);"))
        self.pbIO11.setObjectName(_fromUtf8("pbIO11"))
        self.buttonGroup.addButton(self.pbIO11)
        self.pbIO12 = MyPushButton(self.centralwidget)
        self.pbIO12.setGeometry(QtCore.QRect(390, 160, 51, 31))
        self.pbIO12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO12.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(200, 200, 200);"))
        self.pbIO12.setObjectName(_fromUtf8("pbIO12"))
        self.buttonGroup.addButton(self.pbIO12)
        self.pbIO13 = MyPushButton(self.centralwidget)
        self.pbIO13.setGeometry(QtCore.QRect(390, 190, 51, 31))
        self.pbIO13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO13.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(200, 200, 200);"))
        self.pbIO13.setObjectName(_fromUtf8("pbIO13"))
        self.buttonGroup.addButton(self.pbIO13)
        self.pbIO14 = MyPushButton(self.centralwidget)
        self.pbIO14.setEnabled(True)
        self.pbIO14.setGeometry(QtCore.QRect(390, 220, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.pbIO14.setPalette(palette)
        self.pbIO14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO14.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(127, 127, 127);\n"
"selection-background-color: rgb(127, 127, 127);"))
        self.pbIO14.setObjectName(_fromUtf8("pbIO14"))
        self.buttonGroup.addButton(self.pbIO14)
        self.pbIO15 = MyPushButton(self.centralwidget)
        self.pbIO15.setGeometry(QtCore.QRect(390, 250, 51, 31))
        self.pbIO15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO15.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(200, 200, 200);"))
        self.pbIO15.setObjectName(_fromUtf8("pbIO15"))
        self.buttonGroup.addButton(self.pbIO15)
        self.pbIO16 = MyPushButton(self.centralwidget)
        self.pbIO16.setGeometry(QtCore.QRect(390, 280, 51, 31))
        self.pbIO16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO16.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO16.setObjectName(_fromUtf8("pbIO16"))
        self.buttonGroup.addButton(self.pbIO16)
        self.pbIO17 = MyPushButton(self.centralwidget)
        self.pbIO17.setGeometry(QtCore.QRect(390, 310, 51, 31))
        self.pbIO17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO17.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO17.setObjectName(_fromUtf8("pbIO17"))
        self.buttonGroup.addButton(self.pbIO17)
        self.pbIO18 = MyPushButton(self.centralwidget)
        self.pbIO18.setGeometry(QtCore.QRect(390, 340, 51, 31))
        self.pbIO18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO18.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO18.setObjectName(_fromUtf8("pbIO18"))
        self.buttonGroup.addButton(self.pbIO18)
        self.pbIO19 = MyPushButton(self.centralwidget)
        self.pbIO19.setGeometry(QtCore.QRect(390, 370, 51, 31))
        self.pbIO19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO19.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO19.setObjectName(_fromUtf8("pbIO19"))
        self.buttonGroup.addButton(self.pbIO19)
        self.pbIO20 = MyPushButton(self.centralwidget)
        self.pbIO20.setGeometry(QtCore.QRect(360, 405, 31, 41))
        self.pbIO20.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO20.setObjectName(_fromUtf8("pbIO20"))
        self.buttonGroup.addButton(self.pbIO20)
        self.pbIO21 = MyPushButton(self.centralwidget)
        self.pbIO21.setGeometry(QtCore.QRect(330, 405, 31, 41))
        self.pbIO21.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO21.setObjectName(_fromUtf8("pbIO21"))
        self.buttonGroup.addButton(self.pbIO21)
        self.pbIO22 = MyPushButton(self.centralwidget)
        self.pbIO22.setGeometry(QtCore.QRect(300, 405, 31, 41))
        self.pbIO22.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO22.setObjectName(_fromUtf8("pbIO22"))
        self.buttonGroup.addButton(self.pbIO22)
        self.pbIO23 = MyPushButton(self.centralwidget)
        self.pbIO23.setGeometry(QtCore.QRect(270, 405, 31, 41))
        self.pbIO23.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO23.setObjectName(_fromUtf8("pbIO23"))
        self.buttonGroup.addButton(self.pbIO23)
        self.pbIO24 = MyPushButton(self.centralwidget)
        self.pbIO24.setGeometry(QtCore.QRect(240, 405, 31, 41))
        self.pbIO24.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO24.setObjectName(_fromUtf8("pbIO24"))
        self.buttonGroup.addButton(self.pbIO24)
        self.pbIO25 = MyPushButton(self.centralwidget)
        self.pbIO25.setGeometry(QtCore.QRect(210, 405, 31, 41))
        self.pbIO25.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO25.setObjectName(_fromUtf8("pbIO25"))
        self.buttonGroup.addButton(self.pbIO25)
        self.pbIO26 = MyPushButton(self.centralwidget)
        self.pbIO26.setGeometry(QtCore.QRect(180, 405, 31, 41))
        self.pbIO26.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO26.setObjectName(_fromUtf8("pbIO26"))
        self.buttonGroup.addButton(self.pbIO26)
        self.pbIO27 = MyPushButton(self.centralwidget)
        self.pbIO27.setGeometry(QtCore.QRect(150, 405, 31, 41))
        self.pbIO27.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO27.setObjectName(_fromUtf8("pbIO27"))
        self.buttonGroup.addButton(self.pbIO27)
        self.pbIO28 = MyPushButton(self.centralwidget)
        self.pbIO28.setGeometry(QtCore.QRect(120, 405, 31, 41))
        self.pbIO28.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO28.setObjectName(_fromUtf8("pbIO28"))
        self.buttonGroup.addButton(self.pbIO28)
        self.pbIO29 = MyPushButton(self.centralwidget)
        self.pbIO29.setGeometry(QtCore.QRect(90, 405, 31, 41))
        self.pbIO29.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO29.setObjectName(_fromUtf8("pbIO29"))
        self.buttonGroup.addButton(self.pbIO29)
        self.pbIO30 = MyPushButton(self.centralwidget)
        self.pbIO30.setGeometry(QtCore.QRect(40, 370, 51, 31))
        self.pbIO30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO30.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO30.setObjectName(_fromUtf8("pbIO30"))
        self.buttonGroup.addButton(self.pbIO30)
        self.pbIO31 = MyPushButton(self.centralwidget)
        self.pbIO31.setGeometry(QtCore.QRect(40, 340, 51, 31))
        self.pbIO31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO31.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO31.setObjectName(_fromUtf8("pbIO31"))
        self.buttonGroup.addButton(self.pbIO31)
        self.pbIO32 = MyPushButton(self.centralwidget)
        self.pbIO32.setGeometry(QtCore.QRect(40, 310, 51, 31))
        self.pbIO32.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO32.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO32.setObjectName(_fromUtf8("pbIO32"))
        self.buttonGroup.addButton(self.pbIO32)
        self.pbIO33 = MyPushButton(self.centralwidget)
        self.pbIO33.setGeometry(QtCore.QRect(40, 280, 51, 31))
        self.pbIO33.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO33.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO33.setObjectName(_fromUtf8("pbIO33"))
        self.buttonGroup.addButton(self.pbIO33)
        self.pbIO34 = MyPushButton(self.centralwidget)
        self.pbIO34.setGeometry(QtCore.QRect(40, 250, 51, 31))
        self.pbIO34.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO34.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO34.setObjectName(_fromUtf8("pbIO34"))
        self.buttonGroup.addButton(self.pbIO34)
        self.pbIO35 = MyPushButton(self.centralwidget)
        self.pbIO35.setGeometry(QtCore.QRect(40, 220, 51, 31))
        self.pbIO35.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO35.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO35.setObjectName(_fromUtf8("pbIO35"))
        self.buttonGroup.addButton(self.pbIO35)
        self.pbIO36 = MyPushButton(self.centralwidget)
        self.pbIO36.setGeometry(QtCore.QRect(40, 190, 51, 31))
        self.pbIO36.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO36.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO36.setObjectName(_fromUtf8("pbIO36"))
        self.buttonGroup.addButton(self.pbIO36)
        self.pbIO37 = MyPushButton(self.centralwidget)
        self.pbIO37.setGeometry(QtCore.QRect(40, 160, 51, 31))
        self.pbIO37.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO37.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO37.setObjectName(_fromUtf8("pbIO37"))
        self.buttonGroup.addButton(self.pbIO37)
        self.pbIO38 = MyPushButton(self.centralwidget)
        self.pbIO38.setGeometry(QtCore.QRect(40, 130, 51, 31))
        self.pbIO38.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO38.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO38.setObjectName(_fromUtf8("pbIO38"))
        self.buttonGroup.addButton(self.pbIO38)
        self.pbIO39 = MyPushButton(self.centralwidget)
        self.pbIO39.setGeometry(QtCore.QRect(40, 100, 51, 31))
        self.pbIO39.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbIO39.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbIO39.setObjectName(_fromUtf8("pbIO39"))
        self.buttonGroup.addButton(self.pbIO39)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(80, 90, 321, 321))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pbChoose = QtGui.QPushButton(self.centralwidget)
        self.pbChoose.setGeometry(QtCore.QRect(470, 30, 101, 31))
        self.pbChoose.setObjectName(_fromUtf8("pbChoose"))
        self.tbResult = QtGui.QTextBrowser(self.centralwidget)
        self.tbResult.setGeometry(QtCore.QRect(470, 200, 256, 192))
        self.tbResult.setObjectName(_fromUtf8("tbResult"))
        self.pbGenerate = QtGui.QPushButton(self.centralwidget)
        self.pbGenerate.setGeometry(QtCore.QRect(620, 410, 101, 31))
        self.pbGenerate.setObjectName(_fromUtf8("pbGenerate"))
        self.tbLog = QtGui.QTextBrowser(self.centralwidget)
        self.tbLog.setGeometry(QtCore.QRect(470, 80, 256, 101))
        self.tbLog.setObjectName(_fromUtf8("tbLog"))
        self.pbDelete = QtGui.QPushButton(self.centralwidget)
        self.pbDelete.setGeometry(QtCore.QRect(470, 410, 101, 31))
        self.pbDelete.setObjectName(_fromUtf8("pbDelete"))
        self.pbV33 = MyPushButton(self.centralwidget)
        self.pbV33.setGeometry(QtCore.QRect(20, 10, 51, 31))
        self.pbV33.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbV33.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbV33.setObjectName(_fromUtf8("pbV33"))
        self.pbGND = MyPushButton(self.centralwidget)
        self.pbGND.setGeometry(QtCore.QRect(20, 50, 51, 31))
        self.pbGND.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbGND.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pbGND.setObjectName(_fromUtf8("pbGND"))
        self.rbHigh = QtGui.QRadioButton(self.centralwidget)
        self.rbHigh.setGeometry(QtCore.QRect(610, 20, 89, 16))
        self.rbHigh.setObjectName(_fromUtf8("rbHigh"))
        self.buttonGroup_2 = QtGui.QButtonGroup(gpioConfigTool)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.rbHigh)
        self.rbLow = QtGui.QRadioButton(self.centralwidget)
        self.rbLow.setGeometry(QtCore.QRect(610, 40, 89, 16))
        self.rbLow.setObjectName(_fromUtf8("rbLow"))
        self.buttonGroup_2.addButton(self.rbLow)
        gpioConfigTool.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(gpioConfigTool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        gpioConfigTool.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(gpioConfigTool)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        gpioConfigTool.setStatusBar(self.statusbar)

        self.retranslateUi(gpioConfigTool)
        QtCore.QMetaObject.connectSlotsByName(gpioConfigTool)

    def retranslateUi(self, gpioConfigTool):
        gpioConfigTool.setWindowTitle(_translate("gpioConfigTool", "MainWindow", None))
        self.pbIO0.setText(_translate("gpioConfigTool", "io0", None))
        self.pbIO1.setText(_translate("gpioConfigTool", "io1", None))
        self.pbIO2.setText(_translate("gpioConfigTool", "io2", None))
        self.pbIO3.setText(_translate("gpioConfigTool", "io3", None))
        self.pbIO4.setText(_translate("gpioConfigTool", "io4", None))
        self.pbIO5.setText(_translate("gpioConfigTool", "io5", None))
        self.pbIO6.setText(_translate("gpioConfigTool", "io6", None))
        self.pbIO7.setText(_translate("gpioConfigTool", "io7", None))
        self.pbIO8.setText(_translate("gpioConfigTool", "io8", None))
        self.pbIO9.setText(_translate("gpioConfigTool", "io9", None))
        self.pbIO10.setText(_translate("gpioConfigTool", "io10", None))
        self.pbIO11.setText(_translate("gpioConfigTool", "io11", None))
        self.pbIO12.setText(_translate("gpioConfigTool", "io12", None))
        self.pbIO13.setText(_translate("gpioConfigTool", "io13", None))
        self.pbIO14.setText(_translate("gpioConfigTool", "io14", None))
        self.pbIO15.setText(_translate("gpioConfigTool", "io15", None))
        self.pbIO16.setText(_translate("gpioConfigTool", "io16", None))
        self.pbIO17.setText(_translate("gpioConfigTool", "io17", None))
        self.pbIO18.setText(_translate("gpioConfigTool", "io18", None))
        self.pbIO19.setText(_translate("gpioConfigTool", "io19", None))
        self.pbIO20.setText(_translate("gpioConfigTool", "io20", None))
        self.pbIO21.setText(_translate("gpioConfigTool", "io21", None))
        self.pbIO22.setText(_translate("gpioConfigTool", "io22", None))
        self.pbIO23.setText(_translate("gpioConfigTool", "io23", None))
        self.pbIO24.setText(_translate("gpioConfigTool", "io24", None))
        self.pbIO25.setText(_translate("gpioConfigTool", "io25", None))
        self.pbIO26.setText(_translate("gpioConfigTool", "io26", None))
        self.pbIO27.setText(_translate("gpioConfigTool", "io27", None))
        self.pbIO28.setText(_translate("gpioConfigTool", "io28", None))
        self.pbIO29.setText(_translate("gpioConfigTool", "io29", None))
        self.pbIO30.setText(_translate("gpioConfigTool", "io30", None))
        self.pbIO31.setText(_translate("gpioConfigTool", "io31", None))
        self.pbIO32.setText(_translate("gpioConfigTool", "io32", None))
        self.pbIO33.setText(_translate("gpioConfigTool", "io33", None))
        self.pbIO34.setText(_translate("gpioConfigTool", "io34", None))
        self.pbIO35.setText(_translate("gpioConfigTool", "io35", None))
        self.pbIO36.setText(_translate("gpioConfigTool", "io36", None))
        self.pbIO37.setText(_translate("gpioConfigTool", "io37", None))
        self.pbIO38.setText(_translate("gpioConfigTool", "io38", None))
        self.pbIO39.setText(_translate("gpioConfigTool", "io39", None))
        self.pushButton.setText(_translate("gpioConfigTool", "ESP32", None))
        self.pbChoose.setText(_translate("gpioConfigTool", "choose pairs", None))
        self.pbGenerate.setText(_translate("gpioConfigTool", "generate", None))
        self.pbDelete.setText(_translate("gpioConfigTool", "delete", None))
        self.pbV33.setText(_translate("gpioConfigTool", "V33", None))
        self.pbGND.setText(_translate("gpioConfigTool", "GND", None))
        self.rbHigh.setText(_translate("gpioConfigTool", "High", None))
        self.rbLow.setText(_translate("gpioConfigTool", "Low", None))

from extern import *

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    gpioConfigTool = QtGui.QMainWindow()
    ui = Ui_gpioConfigTool()
    ui.setupUi(gpioConfigTool)
    gpioConfigTool.show()
    sys.exit(app.exec_())

